# Generated by Django 6.0 on 2026-01-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
